name: Manual Integration Tests

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to test (optional)'
        required: false
        type: string
      test_s3:
        description: 'Run S3 integration tests'
        required: false
        default: true
        type: boolean
      test_database:
        description: 'Run database integration tests'
        required: false
        default: false
        type: boolean
      test_api:
        description: 'Run external API integration tests'
        required: false
        default: false
        type: boolean
      use_production_creds:
        description: 'Use production credentials (requires additional approval)'
        required: false
        default: false
        type: boolean

env:
  GO_VERSION: "1.21"

jobs:
  setup:
    name: Setup and Validation
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get-ref.outputs.ref }}
      environment: ${{ steps.get-env.outputs.environment }}
    steps:
      - name: Determine checkout ref
        id: get-ref
        run: |
          if [ -n "${{ github.event.inputs.pr_number }}" ]; then
            echo "ref=refs/pull/${{ github.event.inputs.pr_number }}/head" >> $GITHUB_OUTPUT
            echo "::notice::Testing PR #${{ github.event.inputs.pr_number }}"
          else
            echo "ref=${{ github.ref }}" >> $GITHUB_OUTPUT
            echo "::notice::Testing branch ${{ github.ref_name }}"
          fi
      
      - name: Determine environment
        id: get-env
        run: |
          if [ "${{ github.event.inputs.use_production_creds }}" == "true" ]; then
            echo "environment=production-integration" >> $GITHUB_OUTPUT
            echo "::warning::Using production credentials - additional approval required"
          else
            echo "environment=integration-testing" >> $GITHUB_OUTPUT
            echo "::notice::Using staging credentials"
          fi
      
      - name: Validate inputs
        run: |
          if [ "${{ github.event.inputs.test_s3 }}" != "true" ] && \
             [ "${{ github.event.inputs.test_database }}" != "true" ] && \
             [ "${{ github.event.inputs.test_api }}" != "true" ]; then
            echo "::error::At least one test type must be selected"
            exit 1
          fi

  s3-integration:
    name: S3 Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.inputs.test_s3 == 'true'
    environment: ${{ needs.setup.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.setup.outputs.ref }}
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION || 'us-east-1' }}
      
      - name: Run S3 integration tests
        run: |
          go test -v ./tests -tags=integration -s3 \
            -bucket=${{ secrets.TEST_S3_BUCKET }} \
            -timeout=10m
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
          TEST_S3_BUCKET: ${{ secrets.TEST_S3_BUCKET }}
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: s3-test-results
          path: |
            test-results/
            *.log

  database-integration:
    name: Database Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.inputs.test_database == 'true'
    environment: ${{ needs.setup.outputs.environment }}
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.setup.outputs.ref }}
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Run database integration tests
        run: |
          go test -v ./tests -tags=integration -database \
            -timeout=10m
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: testuser
          DB_PASSWORD: testpass
          DB_NAME: testdb
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: database-test-results
          path: |
            test-results/
            *.log

  api-integration:
    name: External API Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.inputs.test_api == 'true'
    environment: ${{ needs.setup.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.setup.outputs.ref }}
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Run API integration tests
        run: |
          go test -v ./tests -tags=integration -api \
            -timeout=10m
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: |
            test-results/
            *.log

  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [s3-integration, database-integration, api-integration]
    if: always()
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      
      - name: Generate summary
        run: |
          echo "## Integration Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -d "s3-test-results" ]; then
            echo "### ✅ S3 Tests" >> $GITHUB_STEP_SUMMARY
            echo "S3 integration tests completed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -d "database-test-results" ]; then
            echo "### ✅ Database Tests" >> $GITHUB_STEP_SUMMARY
            echo "Database integration tests completed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -d "api-test-results" ]; then
            echo "### ✅ API Tests" >> $GITHUB_STEP_SUMMARY
            echo "API integration tests completed" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID:** ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
      
      - name: Comment on PR (if applicable)
        if: github.event.inputs.pr_number != ''
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = ${{ github.event.inputs.pr_number }};
            const run_url = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `🧪 Integration tests have been run manually by @${{ github.actor }}\n\n[View test results](${run_url})`
            });